// <auto-generated />
namespace StarFarm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StarFarm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StarFarm));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:StarFarm/Migrations/202108290350522_StarFarm.Designer.cs
            get { return "202108290350522_StarFarm"; }
=======
            get { return "202108281513502_StarFarm"; }
>>>>>>> 913bdece3df65f2d18d77ecee04bfb1f16a08c46:StarFarm/Migrations/202108281513502_StarFarm.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
