// <auto-generated />
namespace StarFarm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changepricetodouble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changepricetodouble));
        
        string IMigrationMetadata.Id
        {
            get { return "202108201208543_change price to double"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
